"""Configuration constants for NSE Squeeze Scanner"""

# Bollinger Bands settings
BB_PERIOD = 20
BB_STD_DEV = 2.0

# Keltner Channel settings
KC_EMA_PERIOD = 20
KC_ATR_PERIOD = 20  # Standard TTM Squeeze uses 20-period ATR
KC_ATR_MULTIPLIER = 1.5

# Momentum settings
MOMENTUM_LENGTH = 12

# 200 DMA settings
DMA_PERIOD = 200  # 200-day moving average for signal validation

# Data settings
DEFAULT_PERIOD = "6mo"  # 6 months of historical data
MIN_DATA_POINTS = 30  # Minimum data points required for analysis
MIN_DATA_POINTS_DMA = 200  # Minimum data points for 200 DMA calculation

# Scanner settings
MAX_WORKERS = 10  # Parallel threads for fetching data
CACHE_TTL_SECONDS = 300  # 5 minutes cache for scan results

# NSE data source
NSE_EQUITY_URL = "https://archives.nseindia.com/content/equities/EQUITY_L.csv"

# Database
DB_PATH = "data/nse_squeeze.db"

# UI settings
PAGE_SIZE = 50  # Rows per page in scanner table

# Index definitions - Broad Market
INDEX_NIFTY_50 = "NIFTY_50"
INDEX_NIFTY_NEXT_50 = "NIFTY_NEXT_50"
INDEX_NIFTY_MIDCAP_150 = "NIFTY_MIDCAP_150"
INDEX_NIFTY_SMALLCAP_250 = "NIFTY_SMALLCAP_250"
INDEX_NIFTY_MICROCAP_250 = "NIFTY_MICROCAP_250"

# Index definitions - Sectoral
INDEX_NIFTY_AUTO = "NIFTY_AUTO"
INDEX_NIFTY_BANK = "NIFTY_BANK"
INDEX_NIFTY_FINANCIAL = "NIFTY_FINANCIAL_SERVICES"
INDEX_NIFTY_FMCG = "NIFTY_FMCG"
INDEX_NIFTY_IT = "NIFTY_IT"
INDEX_NIFTY_METAL = "NIFTY_METAL"
INDEX_NIFTY_PHARMA = "NIFTY_PHARMA"
INDEX_NIFTY_PSU_BANK = "NIFTY_PSU_BANK"
INDEX_NIFTY_REALTY = "NIFTY_REALTY"
INDEX_NIFTY_ENERGY = "NIFTY_ENERGY"
INDEX_NIFTY_INFRA = "NIFTY_INFRASTRUCTURE"
INDEX_NIFTY_MEDIA = "NIFTY_MEDIA"
INDEX_NIFTY_PRIVATE_BANK = "NIFTY_PRIVATE_BANK"
INDEX_NIFTY_COMMODITIES = "NIFTY_COMMODITIES"
INDEX_NIFTY_CONSUMPTION = "NIFTY_CONSUMPTION"
INDEX_NIFTY_OIL_GAS = "NIFTY_OIL_GAS"
INDEX_NIFTY_HEALTHCARE = "NIFTY_HEALTHCARE"

# Index definitions - Thematic
INDEX_NIFTY_CPSE = "NIFTY_CPSE"
INDEX_NIFTY_GROWSECT15 = "NIFTY_GROWSECT_15"
INDEX_NIFTY_MNC = "NIFTY_MNC"
INDEX_NIFTY_PSE = "NIFTY_PSE"
INDEX_NIFTY_SERV_SECTOR = "NIFTY_SERV_SECTOR"

# Broad Market Indices
BROAD_MARKET_INDICES = [
    INDEX_NIFTY_50,
    INDEX_NIFTY_NEXT_50,
    INDEX_NIFTY_MIDCAP_150,
    INDEX_NIFTY_SMALLCAP_250,
    INDEX_NIFTY_MICROCAP_250
]

# Sectoral Indices
SECTORAL_INDICES = [
    INDEX_NIFTY_AUTO,
    INDEX_NIFTY_BANK,
    INDEX_NIFTY_FINANCIAL,
    INDEX_NIFTY_FMCG,
    INDEX_NIFTY_IT,
    INDEX_NIFTY_METAL,
    INDEX_NIFTY_PHARMA,
    INDEX_NIFTY_PSU_BANK,
    INDEX_NIFTY_REALTY,
    INDEX_NIFTY_ENERGY,
    INDEX_NIFTY_INFRA,
    INDEX_NIFTY_MEDIA,
    INDEX_NIFTY_PRIVATE_BANK,
    INDEX_NIFTY_COMMODITIES,
    INDEX_NIFTY_CONSUMPTION,
    INDEX_NIFTY_OIL_GAS,
    INDEX_NIFTY_HEALTHCARE
]

# Thematic Indices
THEMATIC_INDICES = [
    INDEX_NIFTY_CPSE,
    INDEX_NIFTY_GROWSECT15,
    INDEX_NIFTY_MNC,
    INDEX_NIFTY_PSE,
    INDEX_NIFTY_SERV_SECTOR
]

# All available indices (backward compatible)
AVAILABLE_INDICES = BROAD_MARKET_INDICES + SECTORAL_INDICES + THEMATIC_INDICES

# Index display names
INDEX_DISPLAY_NAMES = {
    # Broad Market
    INDEX_NIFTY_50: "Nifty 50",
    INDEX_NIFTY_NEXT_50: "Nifty Next 50",
    INDEX_NIFTY_MIDCAP_150: "Nifty Midcap 150",
    INDEX_NIFTY_SMALLCAP_250: "Nifty Smallcap 250",
    INDEX_NIFTY_MICROCAP_250: "Nifty Microcap 250",
    # Sectoral
    INDEX_NIFTY_AUTO: "Nifty Auto",
    INDEX_NIFTY_BANK: "Nifty Bank",
    INDEX_NIFTY_FINANCIAL: "Nifty Financial Services",
    INDEX_NIFTY_FMCG: "Nifty FMCG",
    INDEX_NIFTY_IT: "Nifty IT",
    INDEX_NIFTY_METAL: "Nifty Metal",
    INDEX_NIFTY_PHARMA: "Nifty Pharma",
    INDEX_NIFTY_PSU_BANK: "Nifty PSU Bank",
    INDEX_NIFTY_REALTY: "Nifty Realty",
    INDEX_NIFTY_ENERGY: "Nifty Energy",
    INDEX_NIFTY_INFRA: "Nifty Infrastructure",
    INDEX_NIFTY_MEDIA: "Nifty Media",
    INDEX_NIFTY_PRIVATE_BANK: "Nifty Private Bank",
    INDEX_NIFTY_COMMODITIES: "Nifty Commodities",
    INDEX_NIFTY_CONSUMPTION: "Nifty Consumption",
    INDEX_NIFTY_OIL_GAS: "Nifty Oil & Gas",
    INDEX_NIFTY_HEALTHCARE: "Nifty Healthcare",
    # Thematic
    INDEX_NIFTY_CPSE: "Nifty CPSE",
    INDEX_NIFTY_GROWSECT15: "Nifty Growsect 15",
    INDEX_NIFTY_MNC: "Nifty MNC",
    INDEX_NIFTY_PSE: "Nifty PSE",
    INDEX_NIFTY_SERV_SECTOR: "Nifty Services Sector"
}

# Stock counts per index (approximate)
INDEX_STOCK_COUNTS = {
    # Broad Market
    INDEX_NIFTY_50: 50,
    INDEX_NIFTY_NEXT_50: 50,
    INDEX_NIFTY_MIDCAP_150: 150,
    INDEX_NIFTY_SMALLCAP_250: 250,
    INDEX_NIFTY_MICROCAP_250: 250,
    # Sectoral
    INDEX_NIFTY_AUTO: 15,
    INDEX_NIFTY_BANK: 12,
    INDEX_NIFTY_FINANCIAL: 20,
    INDEX_NIFTY_FMCG: 15,
    INDEX_NIFTY_IT: 10,
    INDEX_NIFTY_METAL: 15,
    INDEX_NIFTY_PHARMA: 20,
    INDEX_NIFTY_PSU_BANK: 12,
    INDEX_NIFTY_REALTY: 10,
    INDEX_NIFTY_ENERGY: 10,
    INDEX_NIFTY_INFRA: 30,
    INDEX_NIFTY_MEDIA: 10,
    INDEX_NIFTY_PRIVATE_BANK: 10,
    INDEX_NIFTY_COMMODITIES: 30,
    INDEX_NIFTY_CONSUMPTION: 30,
    INDEX_NIFTY_OIL_GAS: 15,
    INDEX_NIFTY_HEALTHCARE: 20,
    # Thematic
    INDEX_NIFTY_CPSE: 12,
    INDEX_NIFTY_GROWSECT15: 15,
    INDEX_NIFTY_MNC: 30,
    INDEX_NIFTY_PSE: 20,
    INDEX_NIFTY_SERV_SECTOR: 30
}

# Index categories for UI grouping
INDEX_CATEGORIES = {
    'Broad Market': BROAD_MARKET_INDICES,
    'Sectoral': SECTORAL_INDICES,
    'Thematic': THEMATIC_INDICES
}
